INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("89542419S", "Juan", "Saez", "Vega", "Almeria", "C- Mercurio", "618253876", "1992-08-08", "H");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("26902806M", "Salvador", "Sanchez", "Pérez", "Almeria", "C- Real del barrio alto", "950254837", "1991-03-28", "H");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("17105885A", "Pedro", "Heller", "Pagac", "Almeria", "C- Estrella fugaz", NULL, "2000-10-05", "H");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("04233869Y", "José", "Koss", "Bayer", "Almeria", "C- Júpiter", "628349590", "1998-01-28", "H");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("97258166K", "Ismael", "Strosin", "Turcotte", "Almeria", "C- Neptuno", NULL, "1999-05-24", "H");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("82842571K", "Ramon", "Herzog", "Tremblay", "Almeria", "C- Urano", "626351429", "1996-11-21", "H");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("46900725E", "Daniel", "Herman", "Pacocha", "Almeria", "C- Andarax", "679837625", "1997-04-26", "H");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("11578526G", "Inma", "Lakin", "Yundt", "Almeria", "C- Picos de Europa", "678652431", "1998-09-01", "M");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("79089577Y", "Juan", "Gutiérrez", "Lopez", "Almeria", "C- Los pinos", "678652431", "1998-01-01", "H");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("41491230N", "Antonio", "Dominguez", "Guerrero", "Almeria", "C- Cabo de Gata", "626652498", "1999-02-11", "H");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("64753215G", "Irene", "Hernandez", "Martinez", "Almeria", "C- Zapillo", "628452384", "1996-03-12", "M");
INSERT INTO alumno(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("85135690V", "Sonia", "Gea", "Ruiz", "Almeria", "C- Mercurio", "678812017", "1995-04-13", "M");


INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("11105554G", "Zoe", "Ramirez", "Gea", "Almeria", "C- Marte", "618223876", "1979-08-19", "M", 1);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("38223286T", "David", "Schmidt", "Fisher", "Almeria", "C- Venus", "678516294", "1978-01-19", "H", 2);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("79503962T", "Cristina", "Lemke", "Rutherford", "Almeria", "C- Saturno", "669162534", "1977-08-21", "M", 3);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("61142000L", "Esther", "Spencer", "Lakin", "Almeria", "C- Pluton", NULL, "1977-05-19", "M", 4);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("85366986W", "Carmen", "Streich", "Hirthe", "Almeria", "C- Almanzora", NULL, "1971-04-29", "M", 4);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("73571384L", "Alfredo", "Stiedemann", "Morissette", "Almeria", "C- Guadalquivir", "950896725", "1980-02-01", "H", 6);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("82937751G", "Manolo", "Hamill", "Kozey", "Almeria", "C- Duero", "950263514", "1977-01-02", "H", 1);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("80502866Z", "Alejandro", "Kohler", "Schoen", "Almeria", "C- Tajo", "668726354", "1980-03-14", "H", 2);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("10485008K", "Antonio", "Fahey", "Considine", "Almeria", "C- Sierra de los Filabres", NULL, "1982-03-18", "H", 3);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("85869555K", "Guillermo", "Ruecker", "Upton", "Almeria", "C- Sierra de Gador", NULL, "1973-05-05", "H", 4);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("04326833G", "Micaela", "Monahan", "Murray", "Almeria", "C- Veleta", "662765413", "1976-02-25", "H", 5);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("79221403L", "Francesca", "Schowalter", "Muller", "Almeria", "C- Quinto pino", NULL, "1980-10-31", "H", 6);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("13175769N", "Pepe", "Sanchez", "Ruiz", "Almeria", "C- Quinto pino", NULL, "1980-10-16", "H", 1);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("98816696W", "Juan", "Guerrero", "Martinez", "Almeria", "C- Quinto pino", NULL, "1980-11-21", "H", 1);
INSERT INTO profesor(nif,nombre,apellido1,apellido2,ciudad,direccion,telefono,fecha_nacimiento,sexo,id_departamento) VALUES ("77194445M", "Maria", "Dominguez", "Hernandez", "Almeria", "C- Quinto pino", NULL, "1980-12-13", "M", 2);

INSERT INTO grado(nombre) VALUES ("Grado en Ingenieria Agricola (Plan 2015)");
INSERT INTO grado(nombre) VALUES ("Grado en Ingenieria Eléctrica (Plan 2014)");
INSERT INTO grado(nombre) VALUES ("Grado en Ingenieria Electronica Industrial (Plan 2010)");
INSERT INTO grado(nombre) VALUES ("Grado en Ingenieria Informatica (Plan 2015)");
INSERT INTO grado(nombre) VALUES ("Grado en Ingenieria Mecanica (Plan 2010)");
INSERT INTO grado(nombre) VALUES ("Grado en Ingenieria Quimica Industrial (Plan 2010)");
INSERT INTO grado(nombre) VALUES ("Grado en Biotecnologia (Plan 2015)");
INSERT INTO grado(nombre) VALUES ("Grado en Ciencias Ambientales (Plan 2009)");
INSERT INTO grado(nombre) VALUES ("Grado en Matematicas (Plan 2010)");
INSERT INTO grado(nombre) VALUES ("Grado en Quimica (Plan 2009)");


INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("algegra lineal y matematica discreta", 6, "basica", 1, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Calculo", 6, "basica", 1, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Fisica para informatica", 6, "basica", 1, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Introduccion a la programacion", 6, "basica", 1, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Organizacion y gestion de empresas", 6, "basica", 1, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Estadistica", 6, "basica", 1, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Estructura y tecnologia de computadores", 6, "basica", 1, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Fundamentos de electronica", 6, "basica", 1, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Logica y algoritmica", 6, "basica", 1, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Metodologia de la programacion", 6, "basica", 1, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Arquitectura de Computadores", 6, "basica", 2, 1, 3, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Estructura de Datos y Algoritmos I", 6, "obligatoria", 2, 1, 3, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Ingenieria del Software", 6, "obligatoria", 2, 1, 14, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Sistemas Inteligentes", 6, "obligatoria", 2, 1, 3, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Sistemas Operativos", 6, "obligatoria", 2, 1, 14, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Bases de Datos", 6, "basica", 2, 2, 14, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Estructura de Datos y Algoritmos II", 6, "obligatoria", 2, 2, 14, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Fundamentos de Redes de Computadores", 6 ,"obligatoria", 2, 2, 3, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Planificacion y Gestion de Proyectos Informaticos", 6, "obligatoria", 2, 2, 3, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Programacion de Servicios Software", 6, "obligatoria", 2, 2, 14, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Desarrollo de interfaces de usuario", 6, "obligatoria", 3, 1, 14, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Ingenieria de Requisitos", 6, "optativa", 3, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Integracion de las Tecnologias de la Informacion en las Organizaciones", 6, "optativa", 3, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Modelado y Diseño del Software 1", 6, "optativa", 3, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Multiprocesadores", 6, "optativa", 3, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Seguridad y cumplimiento normativo", 6, "optativa", 3, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Sistema de Informacion para las Organizaciones", 6, "optativa", 3, 1, NULL, 4); 
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Tecnologias web", 6, "optativa", 3, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Teoria de codigos y criptografia", 6, "optativa", 3, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Administracion de bases de datos", 6, "optativa", 3, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Herramientas y Métodos de Ingenieria del Software", 6, "optativa", 3, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Informatica industrial y robotica", 6, "optativa", 3, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Ingenieria de Sistemas de Informacion", 6, "optativa", 3, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Modelado y Diseño del Software 2", 6, "optativa", 3, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Negocio Electronico", 6, "optativa", 3, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Periféricos e interfaces", 6, "optativa", 3, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Sistemas de tiempo real", 6, "optativa", 3, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Tecnologias de acceso a red", 6, "optativa", 3, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Tratamiento digital de imagenes", 6, "optativa", 3, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Administracion de redes y sistemas operativos", 6, "optativa", 4, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Almacenes de Datos", 6, "optativa", 4, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Fiabilidad y Gestion de Riesgos", 6, "optativa", 4, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Lineas de Productos Software", 6, "optativa", 4, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Procesos de Ingenieria del Software 1", 6, "optativa", 4, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Tecnologias multimedia", 6, "optativa", 4, 1, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Analisis y planificacion de las TI", 6, "optativa", 4, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Desarrollo Rapido de Aplicaciones", 6, "optativa", 4, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Gestion de la Calidad y de la Innovacion Tecnologica", 6, "optativa", 4, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Inteligencia del Negocio", 6, "optativa", 4, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Procesos de Ingenieria del Software 2", 6, "optativa", 4, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Seguridad Informatica", 6, "optativa", 4, 2, NULL, 4);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Biologia celular", 6, "basica", 1, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Fisica", 6, "basica", 1, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Matematicas I", 6, "basica", 1, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Quimica general", 6, "basica", 1, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Quimica organica", 6, "basica", 1, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Biologia vegetal y animal", 6, "basica", 1, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Bioquimica", 6, "basica", 1, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Genética", 6, "basica", 1, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Matematicas II", 6, "basica", 1, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Microbiologia", 6, "basica", 1, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Botanica agricola", 6, "obligatoria", 2, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Fisiologia vegetal", 6, "obligatoria", 2, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Genética molecular", 6, "obligatoria", 2, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Ingenieria bioquimica", 6, "obligatoria", 2, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Termodinamica y cinética quimica aplicada", 6, "obligatoria", 2, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Biorreactores", 6, "obligatoria", 2, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Biotecnologia microbiana", 6, "obligatoria", 2, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Ingenieria genética", 6, "obligatoria", 2, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Inmunologia", 6, "obligatoria", 2, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Virologia", 6, "obligatoria", 2, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Bases moleculares del desarrollo vegetal", 4.5, "obligatoria", 3, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Fisiologia animal", 4.5, "obligatoria", 3, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Metabolismo y biosintesis de biomoléculas", 6, "obligatoria", 3, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Operaciones de separacion", 6, "obligatoria", 3, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Patologia molecular de plantas", 4.5, "obligatoria", 3, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Técnicas instrumentales basicas", 4.5, "obligatoria", 3, 1, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Bioinformatica", 4.5, "obligatoria", 3, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Biotecnologia de los productos hortofruticulas", 4.5, "obligatoria", 3, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Biotecnologia vegetal", 6, "obligatoria", 3, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Genomica y proteomica", 4.5, "obligatoria", 3, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Procesos biotecnologicos", 6, "obligatoria", 3, 2, NULL, 7);
INSERT INTO asignatura(nombre,creditos,tipo,curso,cuatrimestre,id_profesor,id_grado) VALUES ("Técnicas instrumentales avanzadas", 4.5, "obligatoria", 3, 2, NULL, 7);

INSERT INTO curso_escolar(fecha_inicio,fecha_fin) VALUES (2014, 2015);
INSERT INTO curso_escolar(fecha_inicio,fecha_fin) VALUES (2015, 2016);
INSERT INTO curso_escolar(fecha_inicio,fecha_fin) VALUES (2016, 2017);
INSERT INTO curso_escolar(fecha_inicio,fecha_fin) VALUES (2017, 2018);

INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 1, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 2, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 3, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 4, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 5, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 6, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 7, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 8, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 9, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 10, 1);

INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 1, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 2, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 3, 2);

INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 1, 3);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 2, 3);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 3, 3);

INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 1, 4);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 2, 4);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (1, 3, 4);

INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (2, 1, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (2, 2, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (2, 3, 1);

INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 1, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 2, 1);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 3, 1);

INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 1, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 2, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 3, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 4, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 5, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 6, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 7, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 8, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 9, 2);
INSERT INTO alumno_se_matricula_asignatura(id_alumno,id_asignatura,id_curso_escolar) VALUES (4, 10, 2);